### ISSUE TITLE
chapter2 I have a KeyError: '_labels'

### ISSUE THREAD

**Issue by ghost** [PacktPublishing/PyTorch-Computer-Vision-Cookbook#13]
Traceback (most recent call last):
  File "C:\Users\jewoo\anaconda3\envs\totti\lib\site-packages\pandas\core\indexes\base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas\_libs\index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: '_labels'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/jewoo/PycharmProjects/vision/chapter/customDataset.py", line 37, in <module>
    histo_dataset = histoCancerDataset(data_dir, data_transformer, "train")
  File "C:/Users/jewoo/PycharmProjects/vision/chapter/customDataset.py", line 23, in __init__
    self.labels = [labels_df.loc[filename[:-4]].values[0] for filename in filenames]
  File "C:/Users/jewoo/PycharmProjects/vision/chapter/customDataset.py", line 23, in <listcomp>
    self.labels = [labels_df.loc[filename[:-4]].values[0] for filename in filenames]
  File "C:\Users\jewoo\anaconda3\envs\totti\lib\site-packages\pandas\core\indexing.py", line 1768, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "C:\Users\jewoo\anaconda3\envs\totti\lib\site-packages\pandas\core\indexing.py", line 1965, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "C:\Users\jewoo\anaconda3\envs\totti\lib\site-packages\pandas\core\indexing.py", line 625, in _get_label
    return self.obj._xs(label, axis=axis)
  File "C:\Users\jewoo\anaconda3\envs\totti\lib\site-packages\pandas\core\generic.py", line 3537, in xs
    loc = self.index.get_loc(key)
  File "C:\Users\jewoo\anaconda3\envs\totti\lib\site-packages\pandas\core\indexes\base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas\_libs\index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: '_labels'

**Comment by mave5** [comment]
I think the issue should be in the data path. Can you make sure the data path is correct? 
This line should return the list of image files: 
```python
      # get list of images
        filenames = os.listdir(path2data)
```
 I guess filenames is currently empty for some reason.
